### ISSUE TITLE
Mesh on 3D-surface

### ISSUE THREAD

**Issue by shengdie** [nschloe/dmsh#1]
Hello,

Thank you for your work, could you please implement the 3d-surface mesh like sphere? I tried by myself, but I am not familiar with matlab. Thank you.

**Comment by gdmcbain** [comment]
Interesting but I suspect nontrivial.  Meanwhile, there are a couple of routines for the sphere in [meshzoo](https://github.com/nschloe/meshzoo#sphere-surface).

**Comment by shengdie** [comment]
I knew it, but it is not based on force balance. I like distmesh, because
it generates most equilateral triangles, which is important in FEM
simulations. distmesh offers matlab code for 3d-surface mesh, but I can't
read it😞

Geordie McBain <notifications@github.com> 于2019年6月23日周日 下午8:33写道：

**Comment by nschloe** [comment]
Would be nice to have. Link to code?

**Comment by shengdie** [comment]
> Would be nice to have. Link to code?
In the official site, distmeshsurface.m
http://persson.berkeley.edu/distmesh/distmesh.zip

**Comment by nschloe** [comment]
Way to complicated for me to dive in like that. PRs welcome.

**Comment by nschloe** [comment]
> I knew it, but it is not based on force balance. I like distmesh, because it generates most equilateral triangles

I've improved iso sphere in meshzoo a bit yesterday. In general, you can't get much better than that.

![iso](https://user-images.githubusercontent.com/181628/66906193-877c0500-f007-11e9-8a65-38da566c086b.png)

**Comment by nschloe** [comment]
Alright, it turns out you can actually do a _little_ bit better. I've just added support for surface meshes to [optimesh](https://github.com/nschloe/optimesh#surface-mesh-smoothing) (https://twitter.com/nschloe/status/1184605182396641280), so here's how you get the best spherical mesh:
```python
import meshzoo
import optimesh

points, cells = meshzoo.icosa_sphere(10)

class Sphere:
    def f(self, x):
        return 1.0 - (x[0] ** 2 + x[1] ** 2 + x[2] ** 2)

    def grad(self, x):
        return -2 * x

points, cells = optimesh.cvt.quasi_newton_uniform_full(
    points, cells, 1.0e-2, 100, verbose=False,
    implicit_surface=Sphere(),
    # step_filename_format="out{:03d}.vtk"
)
```
![opt](https://user-images.githubusercontent.com/181628/66965854-766cdb80-f07b-11e9-947f-9fab6aef7b13.png)

dmsh definitely won't be able to do any better, so let's close this.
