### ISSUE TITLE
Difference of more than 1 geometry using DMSH

### ISSUE THREAD

**Issue by senseiMasai** [nschloe/dmsh#34]
I'm trying to create several holes in a Polygon but the Difference method only accepts 2 geometries: The external one and 1 inside.

I would like to know if it's possible to use the method Difference of DMSH for more than 1 geometry. This is one example:

![image](https://user-images.githubusercontent.com/65079951/82732795-bed63100-9d0f-11ea-8d5a-50582ecda624.png)

is it possible to do that with DMSH?

Thank you in advance!

**Comment by nschloe** [comment]
Sure. Form a union of the holes.

**Comment by senseiMasai** [comment]
Thank you so much!
