### ISSUE TITLE
Force mesh to have a node in a specific point

### ISSUE THREAD

**Issue by senseiMasai** [nschloe/dmsh#35]
Hello,

On one side, I'm would like to know if it's possible with DMSH to force mesh to pass through specific point. For instance, I would like to have a mesh node in the center of each small green circle (each circle should be modeled as a mesh node)

![image](https://user-images.githubusercontent.com/65079951/82749193-c2b59200-9da7-11ea-94d8-fd80edf9108b.png)

On the other side, I would like to know if is possible to make coincide the nodes of different regions along each side. For example:

![image](https://user-images.githubusercontent.com/65079951/82749277-58e9b800-9da8-11ea-85e0-f80cb191c518.png)

Thank you in advance!

**Comment by nschloe** [comment]
Define `geo.feature_points`.
