### ISSUE TITLE
determine the number of cells

### ISSUE THREAD

**Issue by mahmoudalbardan** [nschloe/dmsh#36]
Is it possible to insert the number of points (X) as a parameter instead of the edge_size, then perform meshing, so that the number of vertices obtained at the end is the one we chose before. 
Do you have any recommendation??
I did not try to do that because in this case I should modify the source code. 
I tried some methods like choosing the edge_size corresponding the the wanted number of cells but i does not give a good estimate of edge_size.

Any recommendation or help?? thanks

**Comment by nschloe** [comment]
Not possible with dmsh or any mesh software that I know. The only thing you can do is estimate, and that should work pretty well.
