### ISSUE TITLE
Enhancement suggestions

### ISSUE THREAD

**Issue by kayarre** [nschloe/dmsh#4]
Would like to get feedback on approaches to make dmsh the following:

1. More robust
2. More compact
3. Faster

- Implement some sort of adaptive time stepping? RK methods?
- create a new library in c++ and wrap with python
- Other ideas?

**Comment by nschloe** [comment]
> Implement some sort of adaptive time stepping? RK methods?

The pseudo time-stepping in dmsh is a heuristic, not a precise approximation to something, so increasing the precision of the stepper will not help.

> create a new library in c++ and wrap with python

This won't help much. It's the convergence that is slow, and the smaller you get with the edge size, the longer it takes. Not sure about the factor, but it's large, and that won't go away with C++. Besides, C++ will make the project so much harder to maintain.
