### ISSUE TITLE
Creating geoms with multiple holes

### ISSUE THREAD

**Issue by Eslsamu** [nschloe/dmsh#40]
Hi there
Right now there are an issue when taking a .Difference of a .Difference.
I am using your generator for my project (my bachelors thesis actually) and I need geoms with multiple holes.
I will try to fix that, but I first gotta go through your code. 

PS: Your repos on meshing are very good and helpful. Thanks a lot!

**Comment by nschloe** [comment]
Try difference of the domain and the union of holes.

**Comment by Eslsamu** [comment]
That works, thank you.
