### ISSUE TITLE
Compute_tri_areas fails with new meshplex commit

### ISSUE THREAD

**Issue by Eslsamu** [nschloe/dmsh#43]
Let's take this geo (but it happens for every other shape I tried as well):
![0](https://user-images.githubusercontent.com/23154209/91960156-d60ebc80-ed09-11ea-87a9-c432a1e386db.png)

These are the boundary coords:
boundary_e=[[124.0, 18.0], [75.0, 33.0], [51.0, 54.0], [31.0, 86.0], [19.0, 124.0], [14.0, 183.0], [18.0, 221.0], [33.0, 269.0], [64.0, 310.0], [93.0, 326.0], [122.0, 332.0], [185.0, 327.0], [220.0, 311.0], [254.0, 285.0], [254.0, 156.0], [145.0, 156.0], [145.0, 215.0], [193.0, 215.0], [194.0, 248.0], [155.0, 269.0], [130.0, 269.0], [111.0, 260.0], [92.0, 234.0], [84.0, 190.0], [84.0, 159.0], [94.0, 112.0], [110.0, 91.0], [131.0, 81.0], [159.0, 84.0], [184.0, 116.0], [250.0, 101.0], [242.0, 72.0], [216.0, 36.0], [197.0, 25.0], [162.0, 18.0], [125.0, 19.0]]
dmsh.Polygon(boundary_e)
Then "dmsh.generate(geo, edge_size=20, verbose = False)" leads to:

.../python3.6/site-packages/meshplex/base.py", line 17, in compute_tri_areas
    assert numpy.all(vol2 > -1.0e-14)
AssertionError
Fatal Python error: Aborted

This didn't happen when I had a previos version of meshplex. Maybe the last update caused it.

**Comment by nschloe** [comment]
Interesting. Could you provide a full MWE that I can just copy/paste please? This makes it easier for me. (You can also make use of GitHub code fences for clarity.)

**Comment by nschloe** [comment]
Can you also try to produce the easiest shape possible that produces the error? This helps with testing then.

**Comment by Eslsamu** [comment]
For my usecase I am using segments I take from images, so they are all a bit larger.

Very simple cases like geo = dmsh.Polygon([[0,0],[0,1],[2,1],[1,0.5],[2,0]]) with edge size of 0.1 work.

This one causes the same error (first iteration btw)
![0](https://user-images.githubusercontent.com/23154209/91964376-58e64600-ed0f-11ea-84a3-e91b74f59d8c.png)

points: [[43.0, 7.0], [43.0, 191.0], [154.0, 192.0], [156.0, 190.0], [155.0, 7.0]]

**Comment by nschloe** [comment]
I tried to guess what you did. This
```python
import dmsh

geo = dmsh.Polygon([[0, 0], [0, 1], [2, 1], [1, 0.5], [2, 0]])

dmsh.generate(geo, edge_size=20, verbose=False)
```
works without error. This was a waste of my time.

Lesson: _Always provide a full MWE!_

**Comment by Eslsamu** [comment]
As I said, the example you mention works. The other example I provided does not.

**Comment by nschloe** [comment]
> Always provide a full MWE!

**Comment by Eslsamu** [comment]
Ouch, well I mean this is the MWNE I could get.

[[43.0, 7.0], [43.0, 191.0], [154.0, 192.0], [156.0, 190.0], [155.0, 7.0]]

**Comment by nschloe** [comment]
The complete code. I just want to copy-and-paste the whole thing to make sure I'm running the same as you are.

**Comment by Eslsamu** [comment]
def main():
    X, cells = distmesh.generate(dmsh.Polygon([[43.0, 7.0],
                                               [43.0, 191.0], [154.0, 192.0],
                                               [156.0, 190.0], [155.0, 7.0]]), edge_size=20, verbose=False)

if __name__ == '__main__':
    main()

**Comment by nschloe** [comment]
```
  File "/tmp/j.py", line 2
    X, cells = dmsh.generate(dmsh.Polygon([[43.0, 7.0],
    ^
IndentationError: expected an indented block
```
Always use code fences.

**Comment by Eslsamu** [comment]
> ```
>   File "/tmp/j.py", line 2
>     X, cells = dmsh.generate(dmsh.Polygon([[43.0, 7.0],
>     ^
> IndentationError: expected an indented block
> ```
> 
> Always use code fences.

Okay, sorry I didn't know how to do this on a comment here

**Comment by nschloe** [comment]
Should be fixed now. If the issue persists for you, feel free to reopen with an MWE.
