### ISSUE TITLE
Defining a geometry using a distance function

### ISSUE THREAD

**Issue by mchandra** [nschloe/dmsh#45]
Is it possible to use a distance function to implicitly define a geometry and mesh it (as in PyDishMesh)?

E.g. (from PyDistMesh),

```
circle = lambda p: np.sqrt((p**2).sum(1))-1.0
points, cells = dmsh.generate(circle, 0.1)
```

Thanks

**Comment by nschloe** [comment]
I added a section in the main readme on how to do it. https://github.com/nschloe/dmsh#custom-shapes
