### ISSUE TITLE
Boundary Node Identification

### ISSUE THREAD

**Issue by griff10000** [nschloe/dmsh#60]
What is the best way to extract boundary node indices from a finished mesh?

**Comment by nschloe** [comment]
`mesh.is_boundary_point` should do it.

**Comment by griff10000** [comment]
Many thanks for your prompt response. I used the following approach to generate the boundary nodes:
```
import meshplex
mesh = meshplex.MeshTri(X, cells)

idx = np.where(mesh.is_boundary_node == True)
x, y = X[idx,0].flatten(), X[idx,1].flatten()
```
I appreciate that this may not be optimal. However, I wonder if there is way of directly accessing an 'ordered list' of boundary nodes as I assume such a list is being generated for the `show()` function?

**Comment by nschloe** [comment]
Better use the boolean index directly:
```
Xb = X[mesh.is_boundary_node]
```
Or, if you need the coords separately,
```
x, y = X[mesh.is_boundary_node].T
```

**Comment by griff10000** [comment]
Thanks again.

**Comment by ml14je** [comment]
I believe mesh.is_boundary_node is no longer valid? It comes up with AttributeError: 'MeshTri' object has no attribute 'is_boundary_node'

**Comment by nschloe** [comment]
@ml14je Try `is_boundary_point`. ipythons <tab> expansions can also help exploring a module if you're unsure about a method name.
