### ISSUE TITLE
create_edges can no longer be found from MeshTri

### ISSUE THREAD

**Issue by gsoxley** [nschloe/dmsh#70]
`import dmsh

geo = dmsh.Rectangle(-1.0, +2.0, -1.0, +1.0)
X, cells = dmsh.generate(geo, 0.1)`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-53b3f03a3c63> in <module>
      2
      3 geo = dmsh.Rectangle(-1.0, +2.0, -1.0, +1.0)
----> 4 X, cells = dmsh.generate(geo, 0.1)

~/.miniconda/envs/dvlpy/lib/python3.7/site-packages/dmsh/main.py in generate(geo, edge_size, tol, random_seed, show, max_steps, verbose, flip_tol)
    211         delta_t=0.2,
    212         f_scale=1 + 0.4 / 2 ** (dim - 1),  # from the original article
--> 213         flip_tol=flip_tol,
    214     )
    215     points = mesh.points

~/.miniconda/envs/dvlpy/lib/python3.7/site-packages/dmsh/main.py in distmesh_smoothing(mesh, geo, num_feature_points, edge_size_function, max_steps, tol, verbose, show, delta_t, f_scale, flip_tol)
    233 ):
    234     print(type(mesh))
--> 235     mesh.create_edges()
    236
    237     k = 0

AttributeError: 'MeshTri' object has no attribute 'create_edges'

**Comment by nschloe** [comment]
Haha wow, that was like _two_ minutes after the release. What an attentive community! Will fix now.
