### ISSUE TITLE
potentially better force function

### ISSUE THREAD

**Issue by krober10nd** [nschloe/dmsh#85]
* I've been experimenting with this force function from the paper attached Eq. 3.9 
* It indeed converges faster and produces higher mesh qualities than the default DistMesh one. <img width="770" alt="Screen Shot 2021-09-05 at 12 36 56 PM" src="https://user-images.githubusercontent.com/18619644/132134456-d4ca40d6-c469-4de9-a2b5-f639e9a84ed4.png">. 
* Perhaps it would be useful to implement here?

[imp_distmesh2d.pdf](https://github.com/nschloe/dmsh/files/7112006/imp_distmesh2d.pdf)

**Comment by nschloe** [comment]
Interesting! I'll check it out later.

**Comment by nschloe** [comment]
I played around with the other forcing function a little bit and found virtually no improvement. Not sure what the difference to your observations is.

**Comment by krober10nd** [comment]
When building so-called geophysical multiscale meshes with orders of magnitude (like 100-m to 10 km in one domain) variations in mesh size, it converged faster than the Persson-Strang function.

What were your test cases?

**Comment by krober10nd** [comment]
Maybe try the [rectangle with refinement](https://github.com/nschloe/meshgen-comparison#rectangle-with-refinement) case

**Comment by nschloe** [comment]
I tried with a disk mesh. If it's not better for that, I have little hope for other domains tbh.

**Comment by krober10nd** [comment]
I observed  it influenced the rate of convergence of mesh quality. I'd like to run some comparisons at some point and will post them here or on Sm. Feel free to close it of course. Just found the paper interesting.

**Comment by nschloe** [comment]
> I observed it influenced the rate of convergence of mesh quality.

The mesh quality is almost always 98% because the starting grid is so good. I'm not sure how you measure a faster rate convergence.
