### ISSUE TITLE
Can not install with pip on ubuntu conda python 3.8.19

### ISSUE THREAD

**Issue by kelink** [nschloe/dmsh#98]
pip installation is failed due to not match X21 , the mesh required a lower version of X21 while mesh plex require a higher one.

(myenv38) user@user-virtual-machine:~$ python --version
Python 3.8.19
(myenv38) user@user-virtual-machine:~$ pip install dmsh
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting dmsh
  Using cached https://mirrors.aliyun.com/pypi/packages/8e/ae/ce7ed2155a8f65a7230133895c25e8bd1288f2cb99dd1aabcb7db93babd5/dmsh-0.3.2-py3-none-any.whl (45 kB)
Collecting x21<0.5.0,>=0.4.32 (from dmsh)
  Using cached https://mirrors.aliyun.com/pypi/packages/83/5a/f70e0a7f9a7e7cc480c9c83e99f8728a8a2848b3f9b49daf379b50124482/x21-0.4.33-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (67 kB)
Requirement already satisfied: meshplex<0.20.0,>=0.16.0 in ./anaconda3/envs/myenv38/lib/python3.8/site-packages (from dmsh) (0.19.7)
Requirement already satisfied: npx in ./anaconda3/envs/myenv38/lib/python3.8/site-packages (from dmsh) (0.1.6)
Requirement already satisfied: numpy in ./anaconda3/envs/myenv38/lib/python3.8/site-packages (from dmsh) (1.24.4)
Requirement already satisfied: stonefish-license-manager in ./anaconda3/envs/myenv38/lib/python3.8/site-packages (from dmsh) (0.4.36)
Collecting scipy (from dmsh)
  Using cached https://mirrors.aliyun.com/pypi/packages/69/f0/fb07a9548e48b687b8bf2fa81d71aba9cfc548d365046ca1c791e24db99d/scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
INFO: pip is looking at multiple versions of meshplex to determine which version is compatible with other requirements. This could take a while.
Collecting dmsh
  Using cached https://mirrors.aliyun.com/pypi/packages/23/3d/bd237eed0d50fe658241a6689da96b20fde2f5c98d639a261e1ee82fb2f8/dmsh-0.3.1-py3-none-any.whl (42 kB)
Collecting python-license-manager (from dmsh)
  Using cached https://mirrors.aliyun.com/pypi/packages/99/9a/e41f51313cb4b77b365892888ca46505e6aa5e0954a00a83ae72b5d0dee1/python_license_manager-0.2.11-py3-none-any.whl (38 kB)
ERROR: Cannot install dmsh==0.3.1 and meshplex==0.19.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    dmsh 0.3.1 depends on x21<0.5.0 and >=0.4.10
    meshplex 0.19.7 depends on x21>=0.5.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
(myenv38) user@user-virtual-machine:~$ 

<img width="783" alt="failed Error" src="https://github.com/user-attachments/assets/7d05ef70-d600-49ab-a3ac-94efd880e1f9">

**Comment by nschloe** [comment]
Fixed now.
